#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BottleSlot

#include "Basic.hpp"

#include "BottleSlot_classes.hpp"
#include "BottleSlot_parameters.hpp"


namespace SDK
{

// Function BottleSlot.BottleSlot_C.BndEvt__MachineSide_Mid Bottle_K2Node_ComponentBoundEvent_3_Place Item__DelegateSignature
// (BlueprintEvent)

void ABottleSlot_C::BndEvt__MachineSide_Mid_Bottle_K2Node_ComponentBoundEvent_3_Place_Item__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "BndEvt__MachineSide_Mid Bottle_K2Node_ComponentBoundEvent_3_Place Item__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BottleSlot.BottleSlot_C.BndEvt__MachineSide_Mid Bottle_K2Node_ComponentBoundEvent_4_Take Item__DelegateSignature
// (BlueprintEvent)

void ABottleSlot_C::BndEvt__MachineSide_Mid_Bottle_K2Node_ComponentBoundEvent_4_Take_Item__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "BndEvt__MachineSide_Mid Bottle_K2Node_ComponentBoundEvent_4_Take Item__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BottleSlot.BottleSlot_C.Clear
// (BlueprintCallable, BlueprintEvent)

void ABottleSlot_C::Clear()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "Clear");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BottleSlot.BottleSlot_C.ExecuteUbergraph_BottleSlot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABottleSlot_C::ExecuteUbergraph_BottleSlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "ExecuteUbergraph_BottleSlot");

	Params::BottleSlot_C_ExecuteUbergraph_BottleSlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BottleSlot.BottleSlot_C.Explosion Sound
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABottleSlot_C::Explosion_Sound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "Explosion Sound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BottleSlot.BottleSlot_C.Get Map Position
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector*                         Location                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABottleSlot_C::Get_Map_Position(struct FVector* Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "Get Map Position");

	Params::BottleSlot_C_Get_Map_Position Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Location != nullptr)
		*Location = std::move(Parms.Location);
}


// Function BottleSlot.BottleSlot_C.OnRep_Level
// (BlueprintCallable, BlueprintEvent)

void ABottleSlot_C::OnRep_Level()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "OnRep_Level");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BottleSlot.BottleSlot_C.OnRep_Lock
// (BlueprintCallable, BlueprintEvent)

void ABottleSlot_C::OnRep_Lock()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "OnRep_Lock");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BottleSlot.BottleSlot_C.OnRep_State
// (BlueprintCallable, BlueprintEvent)

void ABottleSlot_C::OnRep_State()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "OnRep_State");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BottleSlot.BottleSlot_C.OverPressure Tick
// (BlueprintCallable, BlueprintEvent)

void ABottleSlot_C::OverPressure_Tick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "OverPressure Tick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BottleSlot.BottleSlot_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABottleSlot_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BottleSlot.BottleSlot_C.Set Pressure
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Pressure_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABottleSlot_C::Set_Pressure(int32 Pressure_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "Set Pressure");

	Params::BottleSlot_C_Set_Pressure Parms{};

	Parms.Pressure_0 = Pressure_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BottleSlot.BottleSlot_C.Set State
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABottleSlot_C::Set_State(int32 TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "Set State");

	Params::BottleSlot_C_Set_State Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BottleSlot.BottleSlot_C.Try Set State
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABottleSlot_C::Try_Set_State(int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "Try Set State");

	Params::BottleSlot_C_Try_Set_State Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BottleSlot.BottleSlot_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABottleSlot_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BottleSlot_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

