#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPL_Items

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "E_Logic_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPL_Items.BPL_Items_C
// 0x0000 (0x0028 - 0x0028)
class UBPL_Items_C final : public UBlueprintFunctionLibrary
{
public:
	static void Set_Item_Materials(class UPrimitiveComponent* Mesh, E_Logic Logic, const struct FStr_ItemState& State, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPL_Items_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPL_Items_C")
	}
	static class UBPL_Items_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPL_Items_C>();
	}
};
DUMPER7_ASSERTS_UBPL_Items_C;

}

