#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Data_SkinCustom_EyeColor

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Data_PlayerCustom_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Data_SkinCustom_EyeColor.Data_SkinCustom_EyeColor_C
// 0x0008 (0x00F0 - 0x00E8)
class UData_SkinCustom_EyeColor_C final : public UData_PlayerCustom_C
{
public:
	uint8                                         Pad_E1[0x3];                                       // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FColor                                 Eye_Color_L;                                       // 0x00E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FColor                                 Eye_Color_R;                                       // 0x00E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Data_SkinCustom_EyeColor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Data_SkinCustom_EyeColor_C")
	}
	static class UData_SkinCustom_EyeColor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UData_SkinCustom_EyeColor_C>();
	}
};
DUMPER7_ASSERTS_UData_SkinCustom_EyeColor_C;

}

