#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Data_Skin_Patch

#include "Basic.hpp"

#include "Data_Skin_Element_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Data_Skin_Patch.Data_Skin_Patch_C
// 0x0008 (0x0228 - 0x0220)
class UData_Skin_Patch_C final : public UData_Skin_Element_C
{
public:
	class UMaterialInstance*                      Material;                                          // 0x0220(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Data_Skin_Patch_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Data_Skin_Patch_C")
	}
	static class UData_Skin_Patch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UData_Skin_Patch_C>();
	}
};
DUMPER7_ASSERTS_UData_Skin_Patch_C;

}

