#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HeavyWeaponCase

#include "Basic.hpp"

#include "HeavyWeaponCase_classes.hpp"
#include "HeavyWeaponCase_parameters.hpp"


namespace SDK
{

// Function HeavyWeaponCase.HeavyWeaponCase_C.All Set AO
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Intensity                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHeavyWeaponCase_C::All_Set_AO(double Intensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "All Set AO");

	Params::HeavyWeaponCase_C_All_Set_AO Parms{};

	Parms.Intensity = Intensity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.BndEvt__WeaponCaseBox_Item Slot_K2Node_ComponentBoundEvent_0_Take Item__DelegateSignature
// (BlueprintEvent)

void AHeavyWeaponCase_C::BndEvt__WeaponCaseBox_Item_Slot_K2Node_ComponentBoundEvent_0_Take_Item__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "BndEvt__WeaponCaseBox_Item Slot_K2Node_ComponentBoundEvent_0_Take Item__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.Clear
// (BlueprintCallable, BlueprintEvent)

void AHeavyWeaponCase_C::Clear()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "Clear");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.ExecuteUbergraph_HeavyWeaponCase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHeavyWeaponCase_C::ExecuteUbergraph_HeavyWeaponCase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "ExecuteUbergraph_HeavyWeaponCase");

	Params::HeavyWeaponCase_C_ExecuteUbergraph_HeavyWeaponCase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.OnRep_Case Open
// (BlueprintCallable, BlueprintEvent)

void AHeavyWeaponCase_C::OnRep_Case_Open()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "OnRep_Case Open");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.OnRep_Selected Weapon
// (HasDefaults, BlueprintCallable, BlueprintEvent)

void AHeavyWeaponCase_C::OnRep_Selected_Weapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "OnRep_Selected Weapon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.Open Case
// (BlueprintCallable, BlueprintEvent)

void AHeavyWeaponCase_C::Open_Case()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "Open Case");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AHeavyWeaponCase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.Set Weapon
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_WeaponListCase                     Weapon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHeavyWeaponCase_C::Set_Weapon(Enum_WeaponListCase Weapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "Set Weapon");

	Params::HeavyWeaponCase_C_Set_Weapon Parms{};

	Parms.Weapon = Weapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.TL Case Opening__FinishedFunc
// (BlueprintEvent)

void AHeavyWeaponCase_C::TL_Case_Opening__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "TL Case Opening__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.TL Case Opening__UpdateFunc
// (BlueprintEvent)

void AHeavyWeaponCase_C::TL_Case_Opening__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "TL Case Opening__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HeavyWeaponCase.HeavyWeaponCase_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AHeavyWeaponCase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HeavyWeaponCase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

