#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemSlot

#include "Basic.hpp"

#include "ItemSlot_classes.hpp"
#include "ItemSlot_parameters.hpp"


namespace SDK
{

// Function ItemSlot.ItemSlot_C.Get Key
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor**                          Key                                                    (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Get_Key(class AActor** Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Get Key");

	Params::ItemSlot_C_Get_Key Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Key != nullptr)
		*Key = Parms.Key;
}


// Function ItemSlot.ItemSlot_C.Get Name
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMec_C*                           Mec                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FString*                          Name_0                                                 (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void AItemSlot_C::Get_Name(class AMec_C* Mec, class FString* Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Get Name");

	Params::ItemSlot_C_Get_Name Parms{};

	Parms.Mec = Mec;

	UObject::ProcessEvent(Func, &Parms);

	if (Name_0 != nullptr)
		*Name_0 = std::move(Parms.Name_0);
}


// Function ItemSlot.ItemSlot_C.Get State
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FStr_ItemState*                  State                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   In                                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Get_State(struct FStr_ItemState* State, bool* In)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Get State");

	Params::ItemSlot_C_Get_State Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (State != nullptr)
		*State = std::move(Parms.State);

	if (In != nullptr)
		*In = Parms.In;
}


// Function ItemSlot.ItemSlot_C.OnRep_Item Data
// (BlueprintCallable, BlueprintEvent)

void AItemSlot_C::OnRep_Item_Data()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "OnRep_Item Data");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ItemSlot.ItemSlot_C.Update Mesh
// (Public, BlueprintCallable, BlueprintEvent)

void AItemSlot_C::Update_Mesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Update Mesh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ItemSlot.ItemSlot_C.Delete Item
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Call_Take_Item                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Delete_Item(bool Call_Take_Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Delete Item");

	Params::ItemSlot_C_Delete_Item Parms{};

	Parms.Call_Take_Item = Call_Take_Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.Force Item
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FStr_ItemState&            Item_State_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Call_Place_Item                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Force_Item(const struct FStr_ItemState& Item_State_0, bool Call_Place_Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Force Item");

	Params::ItemSlot_C_Force_Item Parms{};

	Parms.Item_State_0 = std::move(Item_State_0);
	Parms.Call_Place_Item = Call_Place_Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.Set State
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FStr_ItemState&            Item_State_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Update_Mesh_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Set_State(const struct FStr_ItemState& Item_State_0, bool Update_Mesh_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Set State");

	Params::ItemSlot_C_Set_State Parms{};

	Parms.Item_State_0 = std::move(Item_State_0);
	Parms.Update_Mesh_0 = Update_Mesh_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.Lock
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Locked_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Lock(bool Locked_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Lock");

	Params::ItemSlot_C_Lock Parms{};

	Parms.Locked_0 = Locked_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.Check State
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Item_In_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Locked_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Check_State(bool Item_In_0, bool Locked_0, const struct FStr_ItemState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Check State");

	Params::ItemSlot_C_Check_State Parms{};

	Parms.Item_In_0 = Item_In_0;
	Parms.Locked_0 = Locked_0;
	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AItemSlot_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ItemSlot.ItemSlot_C.Net Interaction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            Item_State_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Net_Interaction(int32 Index_0, class AActor* Source, const struct FStr_ItemState& Item_State_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Net Interaction");

	Params::ItemSlot_C_Net_Interaction Parms{};

	Parms.Index_0 = Index_0;
	Parms.Source = Source;
	Parms.Item_State_0 = std::move(Item_State_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.Local Interaction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            Item_State_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Local_Interaction(int32 Index_0, class AActor* Source, const struct FStr_ItemState& Item_State_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Local Interaction");

	Params::ItemSlot_C_Local_Interaction Parms{};

	Parms.Index_0 = Index_0;
	Parms.Source = Source;
	Parms.Item_State_0 = std::move(Item_State_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.Other Interaction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            Item_State_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Other_Interaction(int32 Index_0, class AActor* Source, const struct FStr_ItemState& Item_State_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Other Interaction");

	Params::ItemSlot_C_Other_Interaction Parms{};

	Parms.Index_0 = Index_0;
	Parms.Source = Source;
	Parms.Item_State_0 = std::move(Item_State_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AItemSlot_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ItemSlot.ItemSlot_C.BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_0_Net Trigger__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AMec_C*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_0_Net_Trigger__DelegateSignature(class AMec_C* Source, const struct FStr_ItemState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_0_Net Trigger__DelegateSignature");

	Params::ItemSlot_C_BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_0_Net_Trigger__DelegateSignature Parms{};

	Parms.Source = Source;
	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_1_Net Trigger__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AMec_C*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_1_Net_Trigger__DelegateSignature(class AMec_C* Source, const struct FStr_ItemState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_1_Net Trigger__DelegateSignature");

	Params::ItemSlot_C_BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_1_Net_Trigger__DelegateSignature Parms{};

	Parms.Source = Source;
	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.Update
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Item_In_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Locked_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Update(bool Item_In_0, bool Locked_0, const struct FStr_ItemState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Update");

	Params::ItemSlot_C_Update Parms{};

	Parms.Item_In_0 = Item_In_0;
	Parms.Locked_0 = Locked_0;
	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_2_Focus__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_2_Focus__DelegateSignature(bool TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_2_Focus__DelegateSignature");

	Params::ItemSlot_C_BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_2_Focus__DelegateSignature Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_3_Focusable__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_3_Focusable__DelegateSignature(bool TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_3_Focusable__DelegateSignature");

	Params::ItemSlot_C_BndEvt__ItemSlot_In_K2Node_ComponentBoundEvent_3_Focusable__DelegateSignature Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_4_Focus__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_4_Focus__DelegateSignature(bool TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_4_Focus__DelegateSignature");

	Params::ItemSlot_C_BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_4_Focus__DelegateSignature Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_5_Focusable__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_5_Focusable__DelegateSignature(bool TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_5_Focusable__DelegateSignature");

	Params::ItemSlot_C_BndEvt__ItemSlot_Out_K2Node_ComponentBoundEvent_5_Focusable__DelegateSignature Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.All Sound
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Place_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UData_Item_C*                     Data                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::All_Sound(bool Place_0, class UData_Item_C* Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "All Sound");

	Params::ItemSlot_C_All_Sound Parms{};

	Parms.Place_0 = Place_0;
	Parms.Data = Data;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.Hit Sphere
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FStr_ItemState&            State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Hit_Sphere(const struct FStr_ItemState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Hit Sphere");

	Params::ItemSlot_C_Hit_Sphere Parms{};

	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.Set Sphere Collision
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Set_Sphere_Collision(bool TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Set Sphere Collision");

	Params::ItemSlot_C_Set_Sphere_Collision Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.BndEvt__ItemSlot_Take_K2Node_ComponentBoundEvent_6_Local Trigger__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AMec_C*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::BndEvt__ItemSlot_Take_K2Node_ComponentBoundEvent_6_Local_Trigger__DelegateSignature(class AMec_C* Source, const struct FStr_ItemState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "BndEvt__ItemSlot_Take_K2Node_ComponentBoundEvent_6_Local Trigger__DelegateSignature");

	Params::ItemSlot_C_BndEvt__ItemSlot_Take_K2Node_ComponentBoundEvent_6_Local_Trigger__DelegateSignature Parms{};

	Parms.Source = Source;
	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.BndEvt__ItemSlot_Place_K2Node_ComponentBoundEvent_7_Local Trigger__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AMec_C*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::BndEvt__ItemSlot_Place_K2Node_ComponentBoundEvent_7_Local_Trigger__DelegateSignature(class AMec_C* Source, const struct FStr_ItemState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "BndEvt__ItemSlot_Place_K2Node_ComponentBoundEvent_7_Local Trigger__DelegateSignature");

	Params::ItemSlot_C_BndEvt__ItemSlot_Place_K2Node_ComponentBoundEvent_7_Local_Trigger__DelegateSignature Parms{};

	Parms.Source = Source;
	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.Set Data
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UData_Item_C*                     Data                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::Set_Data(class UData_Item_C* Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "Set Data");

	Params::ItemSlot_C_Set_Data Parms{};

	Parms.Data = Data;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemSlot.ItemSlot_C.ExecuteUbergraph_ItemSlot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItemSlot_C::ExecuteUbergraph_ItemSlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemSlot_C", "ExecuteUbergraph_ItemSlot");

	Params::ItemSlot_C_ExecuteUbergraph_ItemSlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

