#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Item_Spawner

#include "Basic.hpp"

#include "Item_Spawner_classes.hpp"
#include "Item_Spawner_parameters.hpp"


namespace SDK
{

// Function Item_Spawner.Item_Spawner_C.Clear Used
// (BlueprintCallable, BlueprintEvent)

void AItem_Spawner_C::Clear_Used()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Item_Spawner_C", "Clear Used");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Item_Spawner.Item_Spawner_C.ExecuteUbergraph_Item_Spawner
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AItem_Spawner_C::ExecuteUbergraph_Item_Spawner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Item_Spawner_C", "ExecuteUbergraph_Item_Spawner");

	Params::Item_Spawner_C_ExecuteUbergraph_Item_Spawner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Item_Spawner.Item_Spawner_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AItem_Spawner_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Item_Spawner_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Item_Spawner.Item_Spawner_C.Spawn Item
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FStr_Item&                 Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AItem_Spawner_C::Spawn_Item(const struct FStr_Item& Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Item_Spawner_C", "Spawn Item");

	Params::Item_Spawner_C_Spawn_Item Parms{};

	Parms.Item = std::move(Item);

	UObject::ProcessEvent(Func, &Parms);
}

}

