#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RenderZone

#include "Basic.hpp"

#include "RenderZone_classes.hpp"
#include "RenderZone_parameters.hpp"


namespace SDK
{

// Function RenderZone.RenderZone_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ARenderZone_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RenderZone_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

