#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Str_SpawnsArray

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Str_SpawnsArray.Str_SpawnsArray
// 0x0010 (0x0010 - 0x0000)
struct FStr_SpawnsArray final
{
public:
	TArray<class AMapSpawn_C*>                    Spawns_3_507E3D734A29550E159C32B602FB3540;         // 0x0000(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
};
DUMPER7_ASSERTS_FStr_SpawnsArray;

}

