#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SystemMicControlLite

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class SystemMicControlLite.SystemMicControlLiteBPLibrary
// 0x0000 (0x0028 - 0x0028)
class USystemMicControlLiteBPLibrary final : public UBlueprintFunctionLibrary
{
public:
	static TMap<class FString, class FString> GetMicActiveDevices();
	static class FString GetMicDefaultDeviceId();
	static class FString GetMicDefaultDeviceName();
	static void GetMicDeviceIdFromName(const class FString& InDeviceName, class FString* OutDeviceId);
	static void GetMicDeviceNameFromId(const class FString& InDeviceId, class FString* OutDeviceName);
	static float GetMicVolume();
	static void GetMicVolumeForDeviceId(const class FString& InDeviceId, float* OutVolume);
	static void GetMicVolumeForDeviceName(const class FString& InDeviceName, float* OutVolume);
	static void SetMicVolume(float Value);
	static void SetMicVolumeForDeviceId(const class FString& DeviceID, float Volume);
	static void SetMicVolumeForDeviceName(const class FString& DeviceName, float Volume);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SystemMicControlLiteBPLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SystemMicControlLiteBPLibrary")
	}
	static class USystemMicControlLiteBPLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<USystemMicControlLiteBPLibrary>();
	}
};
DUMPER7_ASSERTS_USystemMicControlLiteBPLibrary;

}

