#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TaskKeyboard

#include "Basic.hpp"

#include "TaskKeyboard_classes.hpp"
#include "TaskKeyboard_parameters.hpp"


namespace SDK
{

// Function TaskKeyboard.TaskKeyboard_C.BndEvt__TaskKeyboard_Down_K2Node_ComponentBoundEvent_1_Button Push__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AMec_C*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ATaskKeyboard_C::BndEvt__TaskKeyboard_Down_K2Node_ComponentBoundEvent_1_Button_Push__DelegateSignature(class AMec_C* Source)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TaskKeyboard_C", "BndEvt__TaskKeyboard_Down_K2Node_ComponentBoundEvent_1_Button Push__DelegateSignature");

	Params::TaskKeyboard_C_BndEvt__TaskKeyboard_Down_K2Node_ComponentBoundEvent_1_Button_Push__DelegateSignature Parms{};

	Parms.Source = Source;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TaskKeyboard.TaskKeyboard_C.BndEvt__TaskKeyboard_Up_K2Node_ComponentBoundEvent_0_Button Push__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AMec_C*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ATaskKeyboard_C::BndEvt__TaskKeyboard_Up_K2Node_ComponentBoundEvent_0_Button_Push__DelegateSignature(class AMec_C* Source)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TaskKeyboard_C", "BndEvt__TaskKeyboard_Up_K2Node_ComponentBoundEvent_0_Button Push__DelegateSignature");

	Params::TaskKeyboard_C_BndEvt__TaskKeyboard_Up_K2Node_ComponentBoundEvent_0_Button_Push__DelegateSignature Parms{};

	Parms.Source = Source;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TaskKeyboard.TaskKeyboard_C.ExecuteUbergraph_TaskKeyboard
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATaskKeyboard_C::ExecuteUbergraph_TaskKeyboard(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TaskKeyboard_C", "ExecuteUbergraph_TaskKeyboard");

	Params::TaskKeyboard_C_ExecuteUbergraph_TaskKeyboard Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TaskKeyboard.TaskKeyboard_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ATaskKeyboard_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TaskKeyboard_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

