#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tuto_Screw

#include "Basic.hpp"

#include "Tuto_Screw_classes.hpp"
#include "Tuto_Screw_parameters.hpp"


namespace SDK
{

// Function Tuto_Screw.Tuto_Screw_C.BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_0_Local Trigger__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AMec_C*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATuto_Screw_C::BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_0_Local_Trigger__DelegateSignature(class AMec_C* Source, const struct FStr_ItemState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_0_Local Trigger__DelegateSignature");

	Params::Tuto_Screw_C_BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_0_Local_Trigger__DelegateSignature Parms{};

	Parms.Source = Source;
	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tuto_Screw.Tuto_Screw_C.BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_1_Net Trigger__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AMec_C*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATuto_Screw_C::BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_1_Net_Trigger__DelegateSignature(class AMec_C* Source, const struct FStr_ItemState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_1_Net Trigger__DelegateSignature");

	Params::Tuto_Screw_C_BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_1_Net_Trigger__DelegateSignature Parms{};

	Parms.Source = Source;
	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tuto_Screw.Tuto_Screw_C.BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_3_Focus__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATuto_Screw_C::BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_3_Focus__DelegateSignature(bool TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_3_Focus__DelegateSignature");

	Params::Tuto_Screw_C_BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_3_Focus__DelegateSignature Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tuto_Screw.Tuto_Screw_C.BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_4_Focusable__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATuto_Screw_C::BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_4_Focusable__DelegateSignature(bool TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_4_Focusable__DelegateSignature");

	Params::Tuto_Screw_C_BndEvt__Button_Interaction_K2Node_ComponentBoundEvent_4_Focusable__DelegateSignature Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tuto_Screw.Tuto_Screw_C.Clear
// (BlueprintCallable, BlueprintEvent)

void ATuto_Screw_C::Clear()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "Clear");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tuto_Screw.Tuto_Screw_C.ExecuteUbergraph_Tuto_Screw
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATuto_Screw_C::ExecuteUbergraph_Tuto_Screw(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "ExecuteUbergraph_Tuto_Screw");

	Params::Tuto_Screw_C_ExecuteUbergraph_Tuto_Screw Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tuto_Screw.Tuto_Screw_C.Get Key
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor**                          Key                                                    (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ATuto_Screw_C::Get_Key(class AActor** Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "Get Key");

	Params::Tuto_Screw_C_Get_Key Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Key != nullptr)
		*Key = Parms.Key;
}


// Function Tuto_Screw.Tuto_Screw_C.Get Name
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMec_C*                           Mec                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FString*                          Name_0                                                 (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void ATuto_Screw_C::Get_Name(class AMec_C* Mec, class FString* Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "Get Name");

	Params::Tuto_Screw_C_Get_Name Parms{};

	Parms.Mec = Mec;

	UObject::ProcessEvent(Func, &Parms);

	if (Name_0 != nullptr)
		*Name_0 = std::move(Parms.Name_0);
}


// Function Tuto_Screw.Tuto_Screw_C.Local Interaction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            Item_State                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATuto_Screw_C::Local_Interaction(int32 Index_0, class AActor* Source, const struct FStr_ItemState& Item_State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "Local Interaction");

	Params::Tuto_Screw_C_Local_Interaction Parms{};

	Parms.Index_0 = Index_0;
	Parms.Source = Source;
	Parms.Item_State = std::move(Item_State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tuto_Screw.Tuto_Screw_C.Net Interaction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            Item_State                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATuto_Screw_C::Net_Interaction(int32 Index_0, class AActor* Source, const struct FStr_ItemState& Item_State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "Net Interaction");

	Params::Tuto_Screw_C_Net_Interaction Parms{};

	Parms.Index_0 = Index_0;
	Parms.Source = Source;
	Parms.Item_State = std::move(Item_State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tuto_Screw.Tuto_Screw_C.Other Interaction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FStr_ItemState&            Item_State                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATuto_Screw_C::Other_Interaction(int32 Index_0, class AActor* Source, const struct FStr_ItemState& Item_State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "Other Interaction");

	Params::Tuto_Screw_C_Other_Interaction Parms{};

	Parms.Index_0 = Index_0;
	Parms.Source = Source;
	Parms.Item_State = std::move(Item_State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tuto_Screw.Tuto_Screw_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ATuto_Screw_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tuto_Screw.Tuto_Screw_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ATuto_Screw_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tuto_Screw.Tuto_Screw_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ATuto_Screw_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tuto_Screw.Tuto_Screw_C.Update Position
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Open_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATuto_Screw_C::Update_Position(bool Open_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "Update Position");

	Params::Tuto_Screw_C_Update_Position Parms{};

	Parms.Open_0 = Open_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tuto_Screw.Tuto_Screw_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ATuto_Screw_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tuto_Screw_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

