#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Banlist_Player

#include "Basic.hpp"

#include "W_Banlist_Player_classes.hpp"
#include "W_Banlist_Player_parameters.hpp"


namespace SDK
{

// Function W_Banlist_Player.W_Banlist_Player_C.BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Banlist_Player_C::BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Banlist_Player.W_Banlist_Player_C.BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Banlist_Player_C::BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Banlist_Player.W_Banlist_Player_C.BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_8_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UW_Banlist_Player_C::BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_8_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_8_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Banlist_Player.W_Banlist_Player_C.BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Banlist_Player_C::BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Banlist_Player.W_Banlist_Player_C.BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Banlist_Player_C::BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Banlist_Player.W_Banlist_Player_C.BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UW_Banlist_Player_C::BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Banlist_Player.W_Banlist_Player_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Banlist_Player_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Banlist_Player.W_Banlist_Player_C.ExecuteUbergraph_W_Banlist_Player
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Banlist_Player_C::ExecuteUbergraph_W_Banlist_Player(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "ExecuteUbergraph_W_Banlist_Player");

	Params::W_Banlist_Player_C_ExecuteUbergraph_W_Banlist_Player Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Banlist_Player.W_Banlist_Player_C.OnGenerateContentWidget
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UW_Banlist_Player_C::OnGenerateContentWidget(class FName Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "OnGenerateContentWidget");

	Params::W_Banlist_Player_C_OnGenerateContentWidget Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_Banlist_Player.W_Banlist_Player_C.OnGenerateItemWidget
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UW_Banlist_Player_C::OnGenerateItemWidget(class FName Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "OnGenerateItemWidget");

	Params::W_Banlist_Player_C_OnGenerateItemWidget Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_Banlist_Player.W_Banlist_Player_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Banlist_Player_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Banlist_Player_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}

}

