#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_BottumScreen

#include "Basic.hpp"

#include "W_BottumScreen_classes.hpp"
#include "W_BottumScreen_parameters.hpp"


namespace SDK
{

// Function W_BottumScreen.W_BottumScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_BottumScreen_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_BottumScreen_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_BottumScreen.W_BottumScreen_C.ExecuteUbergraph_W_BottumScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_BottumScreen_C::ExecuteUbergraph_W_BottumScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_BottumScreen_C", "ExecuteUbergraph_W_BottumScreen");

	Params::W_BottumScreen_C_ExecuteUbergraph_W_BottumScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_BottumScreen.W_BottumScreen_C.Set Mic State
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Open                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_BottumScreen_C::Set_Mic_State(bool Open)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_BottumScreen_C", "Set Mic State");

	Params::W_BottumScreen_C_Set_Mic_State Parms{};

	Parms.Open = Open;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_BottumScreen.W_BottumScreen_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_BottumScreen_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_BottumScreen_C", "Tick");

	Params::W_BottumScreen_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

