#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ItemStats

#include "Basic.hpp"

#include "W_ItemStats_classes.hpp"
#include "W_ItemStats_parameters.hpp"


namespace SDK
{

// Function W_ItemStats.W_ItemStats_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_ItemStats_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemStats_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_ItemStats.W_ItemStats_C.ExecuteUbergraph_W_ItemStats
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ItemStats_C::ExecuteUbergraph_W_ItemStats(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemStats_C", "ExecuteUbergraph_W_ItemStats");

	Params::W_ItemStats_C_ExecuteUbergraph_W_ItemStats Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ItemStats.W_ItemStats_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ItemStats_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemStats_C", "Tick");

	Params::W_ItemStats_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ItemStats.W_ItemStats_C.Update Item
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FStr_Item&                 Item_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_ItemStats_C::Update_Item(const struct FStr_Item& Item_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ItemStats_C", "Update Item");

	Params::W_ItemStats_C_Update_Item Parms{};

	Parms.Item_0 = std::move(Item_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

