#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MapDot

#include "Basic.hpp"

#include "W_MapDot_classes.hpp"
#include "W_MapDot_parameters.hpp"


namespace SDK
{

// Function W_MapDot.W_MapDot_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MapDot_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapDot_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MapDot.W_MapDot_C.ExecuteUbergraph_W_MapDot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MapDot_C::ExecuteUbergraph_W_MapDot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapDot_C", "ExecuteUbergraph_W_MapDot");

	Params::W_MapDot_C_ExecuteUbergraph_W_MapDot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

