#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Menu_Game

#include "Basic.hpp"

#include "W_Menu_Game_classes.hpp"
#include "W_Menu_Game_parameters.hpp"


namespace SDK
{

// Function W_Menu_Game.W_Menu_Game_C.BndEvt__W_Menu_Game_B_Cheat_K2Node_ComponentBoundEvent_4_Pressed__DelegateSignature
// (BlueprintEvent)

void UW_Menu_Game_C::BndEvt__W_Menu_Game_B_Cheat_K2Node_ComponentBoundEvent_4_Pressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "BndEvt__W_Menu_Game_B_Cheat_K2Node_ComponentBoundEvent_4_Pressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Game.W_Menu_Game_C.BndEvt__W_Menu_Game_B_CloseLobby_K2Node_ComponentBoundEvent_1_Pressed__DelegateSignature
// (BlueprintEvent)

void UW_Menu_Game_C::BndEvt__W_Menu_Game_B_CloseLobby_K2Node_ComponentBoundEvent_1_Pressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "BndEvt__W_Menu_Game_B_CloseLobby_K2Node_ComponentBoundEvent_1_Pressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Game.W_Menu_Game_C.BndEvt__W_Menu_Game_B_QuitGame_1_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature
// (BlueprintEvent)

void UW_Menu_Game_C::BndEvt__W_Menu_Game_B_QuitGame_1_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "BndEvt__W_Menu_Game_B_QuitGame_1_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Game.W_Menu_Game_C.BndEvt__W_Menu_Game_B_QuitGame_K2Node_ComponentBoundEvent_0_Pressed__DelegateSignature
// (BlueprintEvent)

void UW_Menu_Game_C::BndEvt__W_Menu_Game_B_QuitGame_K2Node_ComponentBoundEvent_0_Pressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "BndEvt__W_Menu_Game_B_QuitGame_K2Node_ComponentBoundEvent_0_Pressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Game.W_Menu_Game_C.BndEvt__W_Menu_Game_B_StopSession_K2Node_ComponentBoundEvent_2_Pressed__DelegateSignature
// (BlueprintEvent)

void UW_Menu_Game_C::BndEvt__W_Menu_Game_B_StopSession_K2Node_ComponentBoundEvent_2_Pressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "BndEvt__W_Menu_Game_B_StopSession_K2Node_ComponentBoundEvent_2_Pressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Game.W_Menu_Game_C.BndEvt__W_Menu_Game_B_Tuto_K2Node_ComponentBoundEvent_5_Pressed__DelegateSignature
// (BlueprintEvent)

void UW_Menu_Game_C::BndEvt__W_Menu_Game_B_Tuto_K2Node_ComponentBoundEvent_5_Pressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "BndEvt__W_Menu_Game_B_Tuto_K2Node_ComponentBoundEvent_5_Pressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Game.W_Menu_Game_C.BndEvt__W_Menu_Game_BanButton_1_K2Node_ComponentBoundEvent_3_Pressed__DelegateSignature
// (BlueprintEvent)

void UW_Menu_Game_C::BndEvt__W_Menu_Game_BanButton_1_K2Node_ComponentBoundEvent_3_Pressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "BndEvt__W_Menu_Game_BanButton_1_K2Node_ComponentBoundEvent_3_Pressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Game.W_Menu_Game_C.BndEvt__W_Menu_Game_Textbox_SteamID_K2Node_ComponentBoundEvent_8_Text Changed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_Menu_Game_C::BndEvt__W_Menu_Game_Textbox_SteamID_K2Node_ComponentBoundEvent_8_Text_Changed__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "BndEvt__W_Menu_Game_Textbox_SteamID_K2Node_ComponentBoundEvent_8_Text Changed__DelegateSignature");

	Params::W_Menu_Game_C_BndEvt__W_Menu_Game_Textbox_SteamID_K2Node_ComponentBoundEvent_8_Text_Changed__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Menu_Game.W_Menu_Game_C.BndEvt__W_Menu_Session_RefreshButton_1_K2Node_ComponentBoundEvent_6_Pressed__DelegateSignature
// (BlueprintEvent)

void UW_Menu_Game_C::BndEvt__W_Menu_Session_RefreshButton_1_K2Node_ComponentBoundEvent_6_Pressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "BndEvt__W_Menu_Session_RefreshButton_1_K2Node_ComponentBoundEvent_6_Pressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Game.W_Menu_Game_C.ExecuteUbergraph_W_Menu_Game
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Menu_Game_C::ExecuteUbergraph_W_Menu_Game(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "ExecuteUbergraph_W_Menu_Game");

	Params::W_Menu_Game_C_ExecuteUbergraph_W_Menu_Game Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Menu_Game.W_Menu_Game_C.Mec Init
// (BlueprintCallable, BlueprintEvent)

void UW_Menu_Game_C::Mec_Init()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "Mec Init");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Game.W_Menu_Game_C.Menu Refresh
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Menu_Game_C::Menu_Refresh(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "Menu Refresh");

	Params::W_Menu_Game_C_Menu_Refresh Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Menu_Game.W_Menu_Game_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Menu_Game_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Game.W_Menu_Game_C.Update Banlist
// (BlueprintCallable, BlueprintEvent)

void UW_Menu_Game_C::Update_Banlist()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Game_C", "Update Banlist");

	UObject::ProcessEvent(Func, nullptr);
}

}

