#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Settings_Rule

#include "Basic.hpp"

#include "W_Settings_Rule_classes.hpp"
#include "W_Settings_Rule_parameters.hpp"


namespace SDK
{

// Function W_Settings_Rule.W_Settings_Rule_C.BndEvt__W_Settings_Rule_Selection_K2Node_ComponentBoundEvent_1_Value Changed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Rule_C::BndEvt__W_Settings_Rule_Selection_K2Node_ComponentBoundEvent_1_Value_Changed__DelegateSignature(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Rule_C", "BndEvt__W_Settings_Rule_Selection_K2Node_ComponentBoundEvent_1_Value Changed__DelegateSignature");

	Params::W_Settings_Rule_C_BndEvt__W_Settings_Rule_Selection_K2Node_ComponentBoundEvent_1_Value_Changed__DelegateSignature Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Settings_Rule.W_Settings_Rule_C.BndEvt__W_Settings_Rule_Value_K2Node_ComponentBoundEvent_0_Value Changed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// double                                  Value_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Rule_C::BndEvt__W_Settings_Rule_Value_K2Node_ComponentBoundEvent_0_Value_Changed__DelegateSignature(double Value_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Rule_C", "BndEvt__W_Settings_Rule_Value_K2Node_ComponentBoundEvent_0_Value Changed__DelegateSignature");

	Params::W_Settings_Rule_C_BndEvt__W_Settings_Rule_Value_K2Node_ComponentBoundEvent_0_Value_Changed__DelegateSignature Parms{};

	Parms.Value_0 = Value_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Settings_Rule.W_Settings_Rule_C.ExecuteUbergraph_W_Settings_Rule
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Rule_C::ExecuteUbergraph_W_Settings_Rule(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Rule_C", "ExecuteUbergraph_W_Settings_Rule");

	Params::W_Settings_Rule_C_ExecuteUbergraph_W_Settings_Rule Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Settings_Rule.W_Settings_Rule_C.Get Other Random Task
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FName*                            Task                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Rule_C::Get_Other_Random_Task(class FName* Task)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Rule_C", "Get Other Random Task");

	Params::W_Settings_Rule_C_Get_Other_Random_Task Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Task != nullptr)
		*Task = Parms.Task;
}


// Function W_Settings_Rule.W_Settings_Rule_C.Get Valid Tasks Count
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  Value_0                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Rule_C::Get_Valid_Tasks_Count(int32* Value_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Rule_C", "Get Valid Tasks Count");

	Params::W_Settings_Rule_C_Get_Valid_Tasks_Count Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Value_0 != nullptr)
		*Value_0 = Parms.Value_0;
}


// Function W_Settings_Rule.W_Settings_Rule_C.On Rule Change
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Rule_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Rule_C::On_Rule_Change(class FName Rule_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Rule_C", "On Rule Change");

	Params::W_Settings_Rule_C_On_Rule_Change Parms{};

	Parms.Rule_0 = Rule_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Settings_Rule.W_Settings_Rule_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Settings_Rule_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Rule_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Settings_Rule.W_Settings_Rule_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Rule_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Rule_C", "PreConstruct");

	Params::W_Settings_Rule_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Settings_Rule.W_Settings_Rule_C.Update Values
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Rule_C::Update_Values(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Rule_C", "Update Values");

	Params::W_Settings_Rule_C_Update_Values Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

