#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Settings_List_Button

#include "Basic.hpp"

#include "W_Settings_List_Button_classes.hpp"
#include "W_Settings_List_Button_parameters.hpp"


namespace SDK
{

// Function W_Settings_List_Button.W_Settings_List_Button_C.ExecuteUbergraph_W_Settings_List_Button
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_List_Button_C::ExecuteUbergraph_W_Settings_List_Button(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_List_Button_C", "ExecuteUbergraph_W_Settings_List_Button");

	Params::W_Settings_List_Button_C_ExecuteUbergraph_W_Settings_List_Button Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Settings_List_Button.W_Settings_List_Button_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_List_Button_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_List_Button_C", "PreConstruct");

	Params::W_Settings_List_Button_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Settings_List_Button.W_Settings_List_Button_C.Set Selection
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_List_Button_C::Set_Selection(bool TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_List_Button_C", "Set Selection");

	Params::W_Settings_List_Button_C_Set_Selection Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

