#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Session_FriendToInvite

#include "Basic.hpp"

#include "W_Session_FriendToInvite_classes.hpp"
#include "W_Session_FriendToInvite_parameters.hpp"


namespace SDK
{

// Function W_Session_FriendToInvite.W_Session_FriendToInvite_C.BndEvt__W_Session_FriendToInvite_B_Invite_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UW_Session_FriendToInvite_C::BndEvt__W_Session_FriendToInvite_B_Invite_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Session_FriendToInvite_C", "BndEvt__W_Session_FriendToInvite_B_Invite_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Session_FriendToInvite.W_Session_FriendToInvite_C.BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Session_FriendToInvite_C::BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Session_FriendToInvite_C", "BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Session_FriendToInvite.W_Session_FriendToInvite_C.BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Session_FriendToInvite_C::BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Session_FriendToInvite_C", "BndEvt__W_Session_PlayeronList_B_Ban_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Session_FriendToInvite.W_Session_FriendToInvite_C.BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Session_FriendToInvite_C::BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Session_FriendToInvite_C", "BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Session_FriendToInvite.W_Session_FriendToInvite_C.BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Session_FriendToInvite_C::BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Session_FriendToInvite_C", "BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Session_FriendToInvite.W_Session_FriendToInvite_C.BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UW_Session_FriendToInvite_C::BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Session_FriendToInvite_C", "BndEvt__W_Settings_Selection_ButtonL_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Session_FriendToInvite.W_Session_FriendToInvite_C.ExecuteUbergraph_W_Session_FriendToInvite
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Session_FriendToInvite_C::ExecuteUbergraph_W_Session_FriendToInvite(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Session_FriendToInvite_C", "ExecuteUbergraph_W_Session_FriendToInvite");

	Params::W_Session_FriendToInvite_C_ExecuteUbergraph_W_Session_FriendToInvite Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Session_FriendToInvite.W_Session_FriendToInvite_C.OnGenerateContentWidget
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UW_Session_FriendToInvite_C::OnGenerateContentWidget(class FName Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Session_FriendToInvite_C", "OnGenerateContentWidget");

	Params::W_Session_FriendToInvite_C_OnGenerateContentWidget Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_Session_FriendToInvite.W_Session_FriendToInvite_C.OnGenerateItemWidget
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UW_Session_FriendToInvite_C::OnGenerateItemWidget(class FName Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Session_FriendToInvite_C", "OnGenerateItemWidget");

	Params::W_Session_FriendToInvite_C_OnGenerateItemWidget Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_Session_FriendToInvite.W_Session_FriendToInvite_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Session_FriendToInvite_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Session_FriendToInvite_C", "PreConstruct");

	Params::W_Session_FriendToInvite_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

