#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Skin_SkinSelection

#include "Basic.hpp"

#include "W_Skin_SkinSelection_classes.hpp"
#include "W_Skin_SkinSelection_parameters.hpp"


namespace SDK
{

// Function W_Skin_SkinSelection.W_Skin_SkinSelection_C.BndEvt__W_Tablet_ButtonText_W_Tablet_Trigger_K2Node_ComponentBoundEvent_0_On Pressed__DelegateSignature
// (BlueprintEvent)

void UW_Skin_SkinSelection_C::BndEvt__W_Tablet_ButtonText_W_Tablet_Trigger_K2Node_ComponentBoundEvent_0_On_Pressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Skin_SkinSelection_C", "BndEvt__W_Tablet_ButtonText_W_Tablet_Trigger_K2Node_ComponentBoundEvent_0_On Pressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Skin_SkinSelection.W_Skin_SkinSelection_C.BndEvt__W_Tablet_ButtonText_W_Tablet_Trigger_K2Node_ComponentBoundEvent_4_On Enter__DelegateSignature
// (BlueprintEvent)

void UW_Skin_SkinSelection_C::BndEvt__W_Tablet_ButtonText_W_Tablet_Trigger_K2Node_ComponentBoundEvent_4_On_Enter__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Skin_SkinSelection_C", "BndEvt__W_Tablet_ButtonText_W_Tablet_Trigger_K2Node_ComponentBoundEvent_4_On Enter__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Skin_SkinSelection.W_Skin_SkinSelection_C.BndEvt__W_Tablet_ButtonText_W_Tablet_Trigger_K2Node_ComponentBoundEvent_5_On Leave__DelegateSignature
// (BlueprintEvent)

void UW_Skin_SkinSelection_C::BndEvt__W_Tablet_ButtonText_W_Tablet_Trigger_K2Node_ComponentBoundEvent_5_On_Leave__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Skin_SkinSelection_C", "BndEvt__W_Tablet_ButtonText_W_Tablet_Trigger_K2Node_ComponentBoundEvent_5_On Leave__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Skin_SkinSelection.W_Skin_SkinSelection_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Skin_SkinSelection_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Skin_SkinSelection_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Skin_SkinSelection.W_Skin_SkinSelection_C.ExecuteUbergraph_W_Skin_SkinSelection
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Skin_SkinSelection_C::ExecuteUbergraph_W_Skin_SkinSelection(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Skin_SkinSelection_C", "ExecuteUbergraph_W_Skin_SkinSelection");

	Params::W_Skin_SkinSelection_C_ExecuteUbergraph_W_Skin_SkinSelection Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Skin_SkinSelection.W_Skin_SkinSelection_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Skin_SkinSelection_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Skin_SkinSelection_C", "PreConstruct");

	Params::W_Skin_SkinSelection_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Skin_SkinSelection.W_Skin_SkinSelection_C.Rename
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Text_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UW_Skin_SkinSelection_C::Rename(const class FString& Text_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Skin_SkinSelection_C", "Rename");

	Params::W_Skin_SkinSelection_C_Rename Parms{};

	Parms.Text_0 = std::move(Text_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Skin_SkinSelection.W_Skin_SkinSelection_C.Reset
// (BlueprintCallable, BlueprintEvent)

void UW_Skin_SkinSelection_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Skin_SkinSelection_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Skin_SkinSelection.W_Skin_SkinSelection_C.Select Skin
// (BlueprintCallable, BlueprintEvent)

void UW_Skin_SkinSelection_C::Select_Skin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Skin_SkinSelection_C", "Select Skin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Skin_SkinSelection.W_Skin_SkinSelection_C.Selected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Skin_SkinSelection_C::Selected(bool TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Skin_SkinSelection_C", "Selected");

	Params::W_Skin_SkinSelection_C_Selected Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

