#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeaponFX

#include "Basic.hpp"

#include "WeaponFX_classes.hpp"
#include "WeaponFX_parameters.hpp"


namespace SDK
{

// Function WeaponFX.WeaponFX_C.Bullet Shot
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Light                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AWeaponFX_C::Bullet_Shot(int32 Type, bool Light)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponFX_C", "Bullet Shot");

	Params::WeaponFX_C_Bullet_Shot Parms{};

	Parms.Type = Type;
	Parms.Light = Light;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponFX.WeaponFX_C.ExecuteUbergraph_WeaponFX
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AWeaponFX_C::ExecuteUbergraph_WeaponFX(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponFX_C", "ExecuteUbergraph_WeaponFX");

	Params::WeaponFX_C_ExecuteUbergraph_WeaponFX Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponFX.WeaponFX_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AWeaponFX_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponFX_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

